version: "2.3"

services:
  playground:
    container_name: playground
    build:
      context: ./
      network: host
    ports:
      - "5900:5900"
      - "6000:6000"
      - "1234:1234"
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/scripts
      - ./demos:/demos
      - ./:/repo
    environment:
      - VERSION=0.1
    entrypoint: ["/bin/bash"]